<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Avalonia.Container</Title>
    <Authors>Mario</Authors>
    <Company>Real</Company>
    <Description>DialogService, NavigationService</Description>
    <PackageTags>7.0;8.0;9.0</PackageTags>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.2.5</Version>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.22">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Container.Core\Container.Core.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Dialog\DialogServiceExtension.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="Navigate\NavigationServiceExtension.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>
</Project>
